//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.3
//     from Assets/Scripts/InputSystem/BoardInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @BoardInputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @BoardInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""BoardInputActions"",
    ""maps"": [
        {
            ""name"": ""BoardActionMap"",
            ""id"": ""0a987018-a373-4a0d-962e-a722276ac21a"",
            ""actions"": [
                {
                    ""name"": ""Click"",
                    ""type"": ""Button"",
                    ""id"": ""e0a17a4f-4c42-4549-b24b-da0b42f267a3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""2975c883-6c3a-4103-9b64-6e45c1243a40"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e61750b0-0b00-4f40-92e3-71c1b9fc7b46"",
                    ""path"": ""<Touchscreen>/primaryTouch/tap"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // BoardActionMap
        m_BoardActionMap = asset.FindActionMap("BoardActionMap", throwIfNotFound: true);
        m_BoardActionMap_Click = m_BoardActionMap.FindAction("Click", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // BoardActionMap
    private readonly InputActionMap m_BoardActionMap;
    private List<IBoardActionMapActions> m_BoardActionMapActionsCallbackInterfaces = new List<IBoardActionMapActions>();
    private readonly InputAction m_BoardActionMap_Click;
    public struct BoardActionMapActions
    {
        private @BoardInputActions m_Wrapper;
        public BoardActionMapActions(@BoardInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Click => m_Wrapper.m_BoardActionMap_Click;
        public InputActionMap Get() { return m_Wrapper.m_BoardActionMap; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(BoardActionMapActions set) { return set.Get(); }
        public void AddCallbacks(IBoardActionMapActions instance)
        {
            if (instance == null || m_Wrapper.m_BoardActionMapActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_BoardActionMapActionsCallbackInterfaces.Add(instance);
            @Click.started += instance.OnClick;
            @Click.performed += instance.OnClick;
            @Click.canceled += instance.OnClick;
        }

        private void UnregisterCallbacks(IBoardActionMapActions instance)
        {
            @Click.started -= instance.OnClick;
            @Click.performed -= instance.OnClick;
            @Click.canceled -= instance.OnClick;
        }

        public void RemoveCallbacks(IBoardActionMapActions instance)
        {
            if (m_Wrapper.m_BoardActionMapActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IBoardActionMapActions instance)
        {
            foreach (var item in m_Wrapper.m_BoardActionMapActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_BoardActionMapActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public BoardActionMapActions @BoardActionMap => new BoardActionMapActions(this);
    public interface IBoardActionMapActions
    {
        void OnClick(InputAction.CallbackContext context);
    }
}
